<!-- scripts di base -->
<script type="text/javascript" src="ext/adapter/ext/ext-base.js"></script>
<!--script type="text/javascript" src="ext/ext-all.js"></script-->
<script type="text/javascript" src="ext/ext-all-debug-w-comments.js"></script>

<!-- scripts per la griglia -->
<!--<script type="text/javascript" src="ext/examples/ux/gridfilters/menu/RangeMenu.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/menu/ListMenu.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/GridFilters.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/filter/Filter.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/filter/StringFilter.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/filter/DateFilter.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/filter/ListFilter.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/filter/NumericFilter.js"></script>
<script type="text/javascript" src="ext/examples/ux/gridfilters/filter/BooleanFilter.js"></script>-->
<script type="text/javascript" src="ext/examples/ux/RowExpander.js"></script>
<script type="text/javascript" src="ext/examples/ux/SearchField.js"></script>
<script type="text/javascript" src="ext/examples/ux/fileuploadfield/FileUploadField.js"></script>
<script type="text/javascript" src="ext/examples/ux/GroupSummary.js"></script>

<script type="text/javascript" src="ext/HttpProvider.js"></script>
<script type="text/javascript" src="ext/Printer-all.js"></script>

<!-- localizzazione -->
<script type="text/javascript" src="ext/ext-lang-it.js"></script>
