CREATE OR REPLACE VIEW v_geography_pivot_fy
AS
select Area,Anno,
SUM(IF(agenzia='Totale', IPR, null)) AS Totale,
SUM(IF(agenzia='Totale', NumPratiche, null)) AS TotaleNum,
SUM(IF(agenzia='CITY (24)', IPR, null)) AS City1,
SUM(IF(agenzia='CITY (24)', NumPratiche, null)) AS City1Num,
##SUM(IF(agenzia='CITY (CL)', IPR, null)) AS City2,
##SUM(IF(agenzia='CITY (CL)', NumPratiche, null)) AS City2Num,
##SUM(IF(agenzia='CITY (LR)', IPR, null)) AS City3,
##SUM(IF(agenzia='CITY (LR)', NumPratiche, null)) AS City3Num,
SUM(IF(agenzia='CITY (SP)', IPR, null)) AS CitySP,
SUM(IF(agenzia='CITY (SP)', NumPratiche, null)) AS CitySPNum,
##SUM(IF(agenzia='CREDITGEST (28)', IPR, null)) AS CreditGest,
##SUM(IF(agenzia='CREDITGEST (28)', NumPratiche, null)) AS CreditGestNum,
##SUM(IF(agenzia='CSS (F1)', IPR, null)) AS Css,
##SUM(IF(agenzia='CSS (F1)', NumPratiche, null)) AS CssNum,
SUM(IF(agenzia='EUROCOLLECTION (20)', IPR, null)) AS Eurocollection,
SUM(IF(agenzia='EUROCOLLECTION (20)', NumPratiche, null)) AS EurocollectionNum,
##SUM(IF(agenzia='EUROLEGAL (03)', IPR, null)) AS Eurolegal1,
##SUM(IF(agenzia='EUROLEGAL (03)', NumPratiche, null)) AS Eurolegal1Num,
##SUM(IF(agenzia='EUROLEGAL (L4)', IPR, null)) AS Eurolegal2,
##SUM(IF(agenzia='EUROLEGAL (L4)', NumPratiche, null)) AS Eurolegal2Num,
SUM(IF(agenzia='FIDES (L2)', IPR, null)) AS Fides,
SUM(IF(agenzia='FIDES (L2)', NumPratiche, null)) AS FidesNum,
SUM(IF(agenzia='NCP (31)', IPR, null)) AS Ncp31,
SUM(IF(agenzia='NCP (31)', NumPratiche, null)) AS Ncp31Num,
SUM(IF(agenzia='NICOL (35)', IPR, null)) AS Nicol35,
SUM(IF(agenzia='NICOL (35)', NumPratiche, null)) AS Nicol35Num,
SUM(IF(agenzia='OSIRC (L3)', IPR, null)) AS Osirc,
SUM(IF(agenzia='OSIRC (L3)', NumPratiche, null)) AS OsircNum,
##SUM(IF(agenzia='SERVICE POWER (18)', IPR, null)) AS ServicePower,
##SUM(IF(agenzia='SERVICE POWER (18)', NumPratiche, null)) AS ServicePowerNum,
SUM(IF(agenzia='SETEL (27)', IPR, null)) AS Setel1,
SUM(IF(agenzia='SETEL (27)', NumPratiche, null)) AS Setel1Num,
SUM(IF(agenzia='SETEL (29)', IPR, null)) AS Setel2,
SUM(IF(agenzia='SETEL (29)', NumPratiche, null)) AS Setel2Num,
##SUM(IF(agenzia='SETEL (L5)', IPR, null)) AS Setel3,
##SUM(IF(agenzia='SETEL (L5)', NumPratiche, null)) AS Setel3Num,
SUM(IF(agenzia='SOGEC (S2)', IPR, null)) AS Sogec,
SUM(IF(agenzia='SOGEC (S2)', NumPratiche, null)) AS SogecNum,
SUM(IF(agenzia='STARCREDIT (06)', IPR, null)) AS Starcredit,
SUM(IF(agenzia='STARCREDIT (06)', NumPratiche, null)) AS StarcreditNum,
SUM(IF(agenzia='STING (F2)', IPR, null)) AS Sting,
SUM(IF(agenzia='STING (F2)', NumPratiche, null)) AS StingNum
from v_geography_fy
WHERE TipoFascia=1
GROUP BY Area,Anno
order by idArea;