CREATE 

VIEW `v_experian_client` AS
    SELECT 
        `e`.`IdCliente` AS `IdCliente`,
        `e`.`IdExperian` AS `IdExperian`,
        `e`.`CodCliente` AS `CodCliente`,
        `e`.`OwnData` AS `OwnData`,
        `e`.`DataAnalisi` AS `DataAnalisi`,
        `e`.`Nominativo` AS `Nominativo`,
        `e`.`CodiceFiscale` AS `CodiceFiscale`,
        `e`.`D4CScore` AS `D4CScore`,
        `e`.`D4CScoreIndex` AS `D4CScoreIndex`,
        `e`.`TipoFinanziamento` AS `TipoFinanziamento`,
        `e`.`MotivoFinanziamento` AS `MotivoFinanziamento`,
        `e`.`StatoPagamenti` AS `StatoPagamenti`,
        `e`.`ScadutoNonPagato` AS `ScadutoNonPagato`,
        `e`.`MesiDaUltimoProtesto` AS `MesiDaUltimoProtesto`,
        `e`.`NumProtesti` AS `NumProtesti`,
        `e`.`ImportoTotaleProtesti` AS `ImportoTotaleProtesti`,
        `e`.`MesiDaUltimoDatoPubblico` AS `MesiDaUltimoDatoPubblico`,
        `e`.`MesiDaUltimoDataPregiudizievole` AS `MesiDaUltimoDataPregiudizievole`,
        `e`.`NumDatiPregiudizievoli` AS `NumDatiPregiudizievoli`,
        `e`.`ImportoTotaleDatiPregiudizievoli` AS `ImportoTotaleDatiPregiudizievoli`,
        `e`.`NumRichiesteCredito6mesi` AS `NumRichiesteCredito6mesi`,
        `e`.`ImpRichiesteCredito6mesi` AS `ImpRichiesteCredito6mesi`,
        `e`.`NumRichiesteCredito3mesi` AS `NumRichiesteCredito3mesi`,
        `e`.`NumRichiesteAccettate6mesi` AS `NumRichiesteAccettate6mesi`,
        `e`.`ImpRichiesteAccettate6mesi` AS `ImpRichiesteAccettate6mesi`,
        `e`.`NumRichiesteAccettate3mesi` AS `NumRichiesteAccettate3mesi`,
        `e`.`ImpUltimaRichiestaFinanziata` AS `ImpUltimaRichiestaFinanziata`,
        `e`.`PeggiorStatusSpeciale` AS `PeggiorStatusSpeciale`,
        `e`.`NumContratti12mesi` AS `NumContratti12mesi`,
        `e`.`NumContrattiAttivi` AS `NumContrattiAttivi`,
        `e`.`NumContrattiStatus0` AS `NumContrattiStatus0`,
        `e`.`NumContrattiStatus1_6` AS `NumContrattiStatus1_6`,
        `e`.`NumContrattiStatus1_3` AS `NumContrattiStatus1_3`,
        `e`.`NumContrattiStatus4_5` AS `NumContrattiStatus4_5`,
        `e`.`NumContrattiStatus6` AS `NumContrattiStatus6`,
        `e`.`NumContrattiPeggiorStatus0_2_12mesi` AS `NumContrattiPeggiorStatus0_2_12mesi`,
        `e`.`NumContrattiPeggiorStatus1_2_12mesi` AS `NumContrattiPeggiorStatus1_2_12mesi`,
        `e`.`NumContrattiPeggiorStatus3_5_12mesi` AS `NumContrattiPeggiorStatus3_5_12mesi`,
        `e`.`NumContrattiPeggiorStatus6_12mesi` AS `NumContrattiPeggiorStatus6_12mesi`,
        `e`.`NumContrattiDefault_12mesi` AS `NumContrattiDefault_12mesi`,
        `e`.`PeggiorStatus_1_12mesi` AS `PeggiorStatus_1_12mesi`,
        `e`.`PeggiorStatus_6mesi` AS `PeggiorStatus_6mesi`,
        `e`.`PeggiorStatus_7_12mesi` AS `PeggiorStatus_7_12mesi`,
        `e`.`PeggiorStatusCorrente` AS `PeggiorStatusCorrente`,
        `e`.`NumContrattiEstinti` AS `NumContrattiEstinti`,
        `e`.`NumContrattiEstinti_6mesi` AS `NumContrattiEstinti_6mesi`,
        `e`.`NumContrattiDefault` AS `NumContrattiDefault`,
        `e`.`NumContrattiPerditaCessione` AS `NumContrattiPerditaCessione`,
        `e`.`NumContrattiPerditaCessione_12mesi` AS `NumContrattiPerditaCessione_12mesi`,
        `e`.`MesiDaUltimoContrattoStatus0_12mesi` AS `MesiDaUltimoContrattoStatus0_12mesi`,
        `e`.`MesiDaUltimoContrattoStatus3__6_12mesi` AS `MesiDaUltimoContrattoStatus3__6_12mesi`,
        `e`.`MesiDaUltimoContrattoDefault` AS `MesiDaUltimoContrattoDefault`,
        `e`.`TotaleImpScadutoNonPagato` AS `TotaleImpScadutoNonPagato`,
        `e`.`TotaleImpScadutoNonPagato_Status1_2` AS `TotaleImpScadutoNonPagato_Status1_2`,
        `e`.`TotaleImpScadutoNonPagato_Status3_5` AS `TotaleImpScadutoNonPagato_Status3_5`,
        `e`.`TotaleImpScadutoNonPagato_Status6_8` AS `TotaleImpScadutoNonPagato_Status6_8`,
        `e`.`TotaleSaldoInEssere` AS `TotaleSaldoInEssere`,
        `e`.`TotaleImpegnoMensile` AS `TotaleImpegnoMensile`,
        `e`.`NumContiRevolvingSaldoMinore75percento` AS `NumContiRevolvingSaldoMinore75percento`,
        `e`.`RapportoMaxSaldoLimiteCredito` AS `RapportoMaxSaldoLimiteCredito`,
        `e`.`RapportoSaldoAutoSaldoTotale` AS `RapportoSaldoAutoSaldoTotale`,
        `e`.`RapportoMaxScadutoSaldo` AS `RapportoMaxScadutoSaldo`,
        `e`.`NumPrestitiFinalizzati` AS `NumPrestitiFinalizzati`,
        `e`.`NumPrestitiPersonali` AS `NumPrestitiPersonali`,
        `e`.`NumContiRevolving` AS `NumContiRevolving`
    FROM
        (db_cnc.`experian` `e`
        LEFT JOIN db_cnc.`experian` `succ` ON (((`succ`.`IdCliente` = `e`.`IdCliente`)
            AND (`succ`.`IdExperian` > `e`.`IdExperian`))))
    WHERE
        ISNULL(`succ`.`IdCliente`)